FROM wegenenverkeer/java8

#Vereist deb file in deze directory. Configureer IntellIJ om de artifact hier te plaatsen.
ADD geolatte-nosql_1.5-SNAPSHOT_all.deb /root/

RUN dpkg -i /root/geolatte-nosql_1.5-SNAPSHOT_all.deb